/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package smartbianco2.pkg0.Chefe;

import javax.swing.plaf.basic.BasicInternalFrameUI;

public class Funcionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Funcionarios
     */
    public Funcionarios() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNovoFuncionario = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFuncionarios = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnNovoFuncionario.setBackground(new java.awt.Color(0, 102, 51));
        btnNovoFuncionario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnNovoFuncionario.setText("Novo Funcionario");
        btnNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFuncionarioActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(0, 102, 204));
        btnEditar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(204, 0, 51));
        btnExcluir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lbNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNome.setForeground(new java.awt.Color(0, 0, 0));
        lbNome.setText("Olá, Lucas Silva!");

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Gerenciar Funcionarios.");

        TabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaFuncionarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnNovoFuncionario)
                            .addGap(18, 18, 18)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFuncionarioActionPerformed
        
        GerenciarFuncionarios form = new GerenciarFuncionarios(null, true);
        form.setLocationRelativeTo(this);
        form.setVisible(true); // O código PAUSA aqui até o formulário fechar...

        // ...O código RETOMA aqui quando o formulário fecha!
        if (form.isSalvou()) {
            // Pega os dados digitados lá no formulário através dos métodos que criamos
            String nomeDigitado = form.getNomeFuncionario();
            String CPFDigitado = form.getCPFFuncionario();
            String TelefoneDigitado = form.getTelefoneFuncionario();
            String GeneroDigitado = form.getGeneroFuncionario(); 
            String dataNascDigitado = form.getDataFuncionario();

            Funcionario novo = new Funcionario(nomeDigitado, CPFDigitado, TelefoneDigitado, GeneroDigitado, dataNascDigitado);
            listaFuncionarios.add(novo);            
            
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TabelaFuncionarios.getModel();
            modelo.addRow(new Object[]{form.getNomeFuncionario(), form.getCPFFuncionario(), form.getTelefoneFuncionario(), form.getGeneroFuncionario()});

            javax.swing.JOptionPane.showMessageDialog(this, "Plano cadastrado com sucesso!");
        }
    }//GEN-LAST:event_btnNovoFuncionarioActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        int linhaSelecionada = TabelaFuncionarios.getSelectedRow();

    if (linhaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um funcionário na tabela para editar.");
        return;
    }

    // EM VEZ DE PEGAR DA TABELA: Pegamos o objeto completo direto da nossa lista (com a data!)
    Funcionario func = listaFuncionarios.get(linhaSelecionada);

    // Criamos o formulário passando TODOS os 5 dados originais
    GerenciarFuncionarios form = new GerenciarFuncionarios(null, true);
    form.preencherCampos(func.getNome(), func.getCpf(), func.getTelefone(), func.getGenero(), func.getDataNascimento());

    form.setLocationRelativeTo(this);
    form.setVisible(true); 

    if (form.isSalvou()) {
        // 1. Atualizamos o nosso objeto completo na lista da memória
        func.setNome(form.getNomeFuncionario());
        func.setCpf(form.getCPFFuncionario());
        func.setTelefone(form.getTelefoneFuncionario());
        func.setGenero(form.getGeneroFuncionario());
        func.setDataNascimento(form.getDataFuncionario());

        // 2. Atualizamos a tabela visual com os novos dados digitados
        TabelaFuncionarios.setValueAt(func.getNome(), linhaSelecionada, 0);
        TabelaFuncionarios.setValueAt(func.getCpf(), linhaSelecionada, 1);
        TabelaFuncionarios.setValueAt(func.getTelefone(), linhaSelecionada, 2);
        TabelaFuncionarios.setValueAt(func.getGenero(), linhaSelecionada, 3);

        javax.swing.JOptionPane.showMessageDialog(this, "Funcionário atualizado com sucesso!");
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = TabelaFuncionarios.getSelectedRow();

    if (linhaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um funcionário na tabela para excluir.");
        return;
    }

    int certeza = javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este funcionário?", "Confirmar Exclusão", javax.swing.JOptionPane.YES_NO_OPTION);

    if (certeza == javax.swing.JOptionPane.YES_OPTION) {
        // 1. Remove da nossa lista interna da memória para manter o sincronismo
        listaFuncionarios.remove(linhaSelecionada);

        // 2. Remove a linha visualmente da tabela
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TabelaFuncionarios.getModel();
        modelo.removeRow(linhaSelecionada);

        javax.swing.JOptionPane.showMessageDialog(this, "Funcionário excluído com sucesso!");
    }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaFuncionarios;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovoFuncionario;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNome;
    // End of variables declaration//GEN-END:variables
private java.util.ArrayList<Funcionario> listaFuncionarios = new java.util.ArrayList<>();
}
